### PR TITLE
Fix memory leak on corrupt unicode character

### PR DESCRIPTION
**Pull request by rreuvekamp**
Fix for a memory leak which is hitting us on v3.0.0-rc50.

When a corrupt unicode character is received, mtail stops processing logs and instead buffers them in memory. It happens because a recent change ( c12a012 ) has made it so parsing of bytes in the log buffer to runes is being retried when parsing results in a RuneError. I guess that change was made under the assumption that rune errors are always recoverable (you just need to increase the buffer), but that is not the case. In production we've seen this memory leak happen multiple times since we deployed the new version of mtail.

With this commit RuneErrors on parsing unicode characters are ignored when there are enough characters after it in the buffer.
This keeps the functionality intact that bytes that gave a RuneError are being reparsed, but with a larger buffer, to not break unicode characters which were split in half from the buffered reading on the logfile being read.

### CODE REVIEW

**Review by jaqx0r — APPROVED** [review]
Thanks, this is great!

**Comment by jaqx0r** [comment]
https://github.com/google/mtail/runs/7910805252?check_suite_focus=true has a failure in `make fuzz-regtest`.

There are debugging instructions at https://google.github.io/mtail/debugging.html#fuzzer-crashes

**Comment by rreuvekamp** [comment]
@jaqx0r thank you for the review.

I cannot reproduce the fuzzer fail locally. It seems CI timeouts on a certain test. Could it be that this is a problem in CI and not so much in my patch?

**Comment by jaqx0r** [comment]
Yeah I think so.  I've disabled that from the branch requirements; Can you update your branch and then I can merge it.

**Comment by rreuvekamp** [comment]
Good to know. I've updated the branch

**Review by jaqx0r — APPROVED** [review]

**Comment by jaqx0r** [comment]
Thanks!

**Pull request merged**
