### PR TITLE
Update build.

### PR DESCRIPTION
**Pull request by SuperQ**
* Update to Go 1.13.
* Update all Go dependencies.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
I'm not sure what's up with the coverage build.

**Comment by jaqx0r** [comment]
The coverage failure is why I haven't upgraded to 1.13 yet.

**Comment by SuperQ** [comment]
https://github.com/golang/go/issues/35781 :frowning_face: 

This coverage tool seems to break often.  Maybe try https://codecov.io/ instead? The free plan should be enough for mtail.

**Comment by jaqx0r** [comment]
The problem is with go cover, not with the coverage hosting, unless I've
misread what you're suggesting?

**Comment by SuperQ** [comment]
Yes, I'm suggesting that the coverage tool is not stable enough for use, and that it's worth considering other tools, hosted or not.

**Comment by jaqx0r** [comment]
Oh I see, with codecov.io we don't need to run go tool cover to process the
coverage reports generated by go test?

In fact, I think we don't need go tool cover in mtail either -- If I'm not
mistaken now I've reread the Makefile, it's only being used to generate an
html report, which we don't really need at all.

**Comment by jaqx0r** [comment]
I've removed the errant command from the coverage step in CircleCI's config now, so this should go through fine.

**Comment by jaqx0r** [comment]
Sigh, fine, this needs more work.  Going to disable coverage for now and file an issue to fix it.

**Comment by SuperQ** [comment]
Thanks for merging. That sucks, good luck with the coverage tool issues.

**Pull request merged**
