### PR TITLE
Resolves #82 allow specific bind interface

### LINKED ISSUE #82: option should be added to allow explicitly setting interface on which to bind
the singe `-port` option is implemented in such a way as to make it impossible to selectively bind a specific interface.

It takes a string as an argument, but then that string is passed to `http.ListenAndServe` with a bare colon prepended to cause a default `0.0.0.0` binding. 

https://github.com/google/mtail/blob/master/mtail/mtail.go#L288

I propose that either the code be modified to allow for a full `address:port` being passed from the `-port` flag OR adding an additional `interface/address` flag.

The use case is for exporting metrics on a multihomed machine where it is undesirable to have an http listener on every interface.

### PR DESCRIPTION
**Pull request by drawks**
* Add a bit of logic between parsing flags and instantiating mtail
  instance to decide whether to use an implicit global bind
* Updated `MtailServer` to not munge `port` since the value in `o` is
  already corrected.

### CODE REVIEW

**Comment by drawks** [comment]
@jaqx0r any chance I can get a merge here? It is a very simple change and preserves backwards compatible behavior. Coverage and test unchanged

**Comment by mattbostock** [comment]
@jaqx0r: What should the new flag be called? Usually one might use `addr`, but it seems a lot of the other flags use `hostport`.

**Comment by drawks** [comment]
It doesn't mean "more than just the listening port", it just allows for a more specific selection of the port to bind. `127.0.0.1:3900` is a port just like `3900` is a port, the existing behavior just makes the address portion of the specification implicit while my PR allows for it to be explicitly set.

**Comment by jaqx0r** [comment]
@drawks It does change the meaning of the flag if you add the bind address into the accepted values -- the flag name is "port" and the flag description says "HTTP port to listen on."

If you proceed with the code as written, I would like the flag renamed to "hostport" or "bind_addr" or something, like @mattbostock suggests.

But I also don't want to sacrifice backwards compatibility, so that why I suggested you add a flag for "address", that you can concatenate with port as you have done on main.go:104 in your branch.  I think this choice is simpler (you don't have to check for a ":" in the port string) and preserves backwards compat.

Thanks.

**Comment by drawks** [comment]
I disagree with your assessment, but I'll make the change as requested, because arguing over the detail seems not a good use of energy.

**Comment by jaqx0r** [comment]
Thanks.

**Pull request merged**
