### PR TITLE
Add concat function

### LINKED ISSUE #102: Add support for arbitrary string processing of matched fields
Dear all,
I'm using latest mtail (https://github.com/google/mtail/releases/tag/v3.0.0-rc4) for legacy applications prometheus.io style metric reporting.

I believe mtail is good tool but there are plenty of areas to perform better.

I currently want to combine two matched logfile line fields concatenate them and use product as metric's label `errors_total{type=...}`. Is there a way how to achieve it?

Let's look at my mtail rule snippets:
 * option A (preferred)
```
counter errors_total by app, type

# 5xx requests highlighted as application error
/sortserver '([^\(]+)\(.+ status=(5[0-9]+)/ {
    errors_total["sortserver"][sprintf("%s %s",$1,$2)]++
}
```
 * option B
```
counter errors_total by app, type

# 5xx requests highlighted as application error
/sortserver '([^\(]+)\(.+ status=(5[0-9]+)/ {
    errors_total["sortserver"][$1+" "+$2]++
}
```

I'm basically proposing to add another builtin function `sprintf(...)` wired to golang's `fmt.Sprintf(...)` or at least allow string concatenation with `+` operators.

Thanks in advance for your reply.

### PR DESCRIPTION
**Pull request by lksv**
Adds `concat` function.

It is useful in case when you need construct metric dimension from two parts:

```
counter errors_total by msg

/method=(?P<method>[^ ]+ )status=(?P<status_code>5[0-9]+) / {
    errors_total[concat($1, $2)]++
}
```

fixes #102

### CODE REVIEW

**Comment by lksv** [comment]
I have already signed the CLA.

**Comment by lksv** [comment]
I will re-push the the branch in hope, that googlebot will retest the CLA.

**Comment by freznicek** [comment]
Awesome change! Let's get it to master as rc5 ASAP.

**Comment by jaqx0r** [comment]
I think we should do this with the addition operator which is already misused in the parser for pattern concatenation.  Fixing pattern concat to be the same as string concat is required for making #88 and #103 work, such that patterns can appear as part of a conditional expression instead of starting a conditonal by themselves.

Thanks for the patch though.

**Comment by jaqx0r** [comment]
+ now works for string concatenation.

**Pull request closed without merging**
